version: '3.8'

services:

  # Database
  mysql:
    image: mysql:latest
    container_name: hexagonal-mysql
    restart: always
    environment: 
      MYSQL_DATABASE: 'basic'
      MYSQL_USER: 'basic'
      MYSQL_PASSWORD: 'P@ssw0rd'
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
    ports: 
      - 1234:3306
    expose: 
      - 1234
    volumes: 
      - ./data:/var/lib/mysql